// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBArVKU4mPQL0auGmB9lSKqyLmNEh-0OfU',
    appId: '1:601915109221:web:865bb0ab3dd565a121bb8c',
    messagingSenderId: '601915109221',
    projectId: 'ecommerceapp-f2449',
    authDomain: 'ecommerceapp-f2449.firebaseapp.com',
    storageBucket: 'ecommerceapp-f2449.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD152ibg11X7QykFYGLee1qgjvVmkQ6toU',
    appId: '1:601915109221:android:4a39bfcdf93e431421bb8c',
    messagingSenderId: '601915109221',
    projectId: 'ecommerceapp-f2449',
    storageBucket: 'ecommerceapp-f2449.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8XPzzo2c8K86dKorFN0diTLMDIki4EY4',
    appId: '1:601915109221:ios:fb3b4804f557568321bb8c',
    messagingSenderId: '601915109221',
    projectId: 'ecommerceapp-f2449',
    storageBucket: 'ecommerceapp-f2449.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8XPzzo2c8K86dKorFN0diTLMDIki4EY4',
    appId: '1:601915109221:ios:fb3b4804f557568321bb8c',
    messagingSenderId: '601915109221',
    projectId: 'ecommerceapp-f2449',
    storageBucket: 'ecommerceapp-f2449.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBArVKU4mPQL0auGmB9lSKqyLmNEh-0OfU',
    appId: '1:601915109221:web:82f4a8b14e39ecbd21bb8c',
    messagingSenderId: '601915109221',
    projectId: 'ecommerceapp-f2449',
    authDomain: 'ecommerceapp-f2449.firebaseapp.com',
    storageBucket: 'ecommerceapp-f2449.appspot.com',
  );
}
